### ISSUE TITLE
new Nodemcu V3 doesn't register button press on GPIO 10

### ISSUE THREAD

**Issue by cshunt** [agent-r/bCNC-PENDANT#1]
Interesting project.
For some reason, using GPIO 10 as an input does not seem to work for me.
I was able to compile, the screen would boot up but button press of rotary encoder did not function.
This made it difficult to move forward. I added some Serial.println() debugging bits and found that that button would not register.
A second sketch of just checking for a button press on GPIO 10 failed once I set the pinMode(10, INPUT).
I am not too familar with esp8266 but I assume the pin has multi functions, flash usb, or eeprom.

I changed to GPIO 16 and the project is functioning and connecting!!

#define BUTTON_PIN 16       // rotary encoder button

The other hiccup I had, the ebay tft screen required me to add a pull up wire to the reset pin.

**Comment by agent-r** [comment]
1) Thanks for your feedback. GPIO10 worked for me, but maybe you use a different NodeMCU version. This might also help other users who similar problems.

2) Yes, TFT Reset should be connected to 3V3. This is also written in the Readme.

**Comment by cshunt** [comment]
Thanks for taking a look. I will close the issue, I did see that there is some esp8266 that use different flash memory, if in DIO mode, I believe this enables GPIO pins 9 and 10. I did not see anything obvious about programming the module with arduino IDE and changing the memory mode (maybe selecting a generic module would have more options) so I am continuing to use GPIO 16.
